name: Deploy to Production

on:
  push:
    branches:
    - prod

env:
  NODE_ENV: prod
  GH_TOKEN: ${{ github.token }}

permissions: write-all

jobs:
  deploy-prod:
    name: Deploy (production)
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Rokit dependencies
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Build projects
        run: npx orchestra run build -- -y

      - name: Upload artifacts
        run: npx orchestra run upload -- -s

      - name: Publish to Roblox
        run: npx orchestra run publish -- -s

